//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChannelDLL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPalindromeService")]
    public interface IPalindromeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalindromeService/GetLongestPalindromePrefix", ReplyAction="http://tempuri.org/IPalindromeService/GetLongestPalindromePrefixResponse")]
        string GetLongestPalindromePrefix(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPalindromeService/GetLongestPalindromePrefix", ReplyAction="http://tempuri.org/IPalindromeService/GetLongestPalindromePrefixResponse")]
        System.Threading.Tasks.Task<string> GetLongestPalindromePrefixAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPalindromeServiceChannel : ChannelDLL.ServiceReference1.IPalindromeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PalindromeServiceClient : System.ServiceModel.ClientBase<ChannelDLL.ServiceReference1.IPalindromeService>, ChannelDLL.ServiceReference1.IPalindromeService {
        
        public PalindromeServiceClient() {
        }
        
        public PalindromeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PalindromeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalindromeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalindromeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLongestPalindromePrefix(string input) {
            return base.Channel.GetLongestPalindromePrefix(input);
        }
        
        public System.Threading.Tasks.Task<string> GetLongestPalindromePrefixAsync(string input) {
            return base.Channel.GetLongestPalindromePrefixAsync(input);
        }
    }
}
