
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox RootContainer;

	private global::Gtk.HBox InputContainer;

	private global::Gtk.Label NumbrName;

	private global::Gtk.SpinButton NumberInput;

	private global::Gtk.ScrolledWindow ScrolledTextView;

	private global::Gtk.TextView TextInput;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label ResultLabel;

	private global::Gtk.Entry ResultOutput;

	private global::Gtk.Button SubmitButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.RootContainer = new global::Gtk.VBox();
		this.RootContainer.Name = "RootContainer";
		this.RootContainer.Spacing = 6;
		// Container child RootContainer.Gtk.Box+BoxChild
		this.InputContainer = new global::Gtk.HBox();
		this.InputContainer.Name = "InputContainer";
		this.InputContainer.Homogeneous = true;
		this.InputContainer.Spacing = 6;
		// Container child InputContainer.Gtk.Box+BoxChild
		this.NumbrName = new global::Gtk.Label();
		this.NumbrName.Name = "NumbrName";
		this.NumbrName.LabelProp = global::Mono.Unix.Catalog.GetString("Число:");
		this.NumbrName.UseUnderline = true;
		this.InputContainer.Add(this.NumbrName);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.InputContainer[this.NumbrName]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child InputContainer.Gtk.Box+BoxChild
		this.NumberInput = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.NumberInput.CanFocus = true;
		this.NumberInput.Name = "NumberInput";
		this.NumberInput.Adjustment.PageIncrement = 10D;
		this.NumberInput.ClimbRate = 1D;
		this.NumberInput.Numeric = true;
		this.NumberInput.Value = 1D;
		this.InputContainer.Add(this.NumberInput);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.InputContainer[this.NumberInput]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(5));
		this.RootContainer.Add(this.InputContainer);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.RootContainer[this.InputContainer]));
		w3.Position = 0;
		w3.Expand = false;
		// Container child RootContainer.Gtk.Box+BoxChild
		this.ScrolledTextView = new global::Gtk.ScrolledWindow();
		this.ScrolledTextView.Name = "ScrolledTextView";
		this.ScrolledTextView.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ScrolledTextView.Gtk.Container+ContainerChild
		this.TextInput = new global::Gtk.TextView();
		this.TextInput.CanFocus = true;
		this.TextInput.Name = "TextInput";
		this.TextInput.WrapMode = ((global::Gtk.WrapMode)(2));
		this.ScrolledTextView.Add(this.TextInput);
		this.RootContainer.Add(this.ScrolledTextView);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.RootContainer[this.ScrolledTextView]));
		w5.Position = 1;
		// Container child RootContainer.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ResultLabel = new global::Gtk.Label();
		this.ResultLabel.Name = "ResultLabel";
		this.ResultLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Результат:");
		this.hbox3.Add(this.ResultLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.ResultLabel]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ResultOutput = new global::Gtk.Entry();
		this.ResultOutput.CanFocus = true;
		this.ResultOutput.Name = "ResultOutput";
		this.ResultOutput.IsEditable = false;
		this.ResultOutput.HasFrame = false;
		this.ResultOutput.InvisibleChar = '●';
		this.hbox3.Add(this.ResultOutput);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.ResultOutput]));
		w7.Position = 1;
		this.RootContainer.Add(this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.RootContainer[this.hbox3]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child RootContainer.Gtk.Box+BoxChild
		this.SubmitButton = new global::Gtk.Button();
		this.SubmitButton.CanFocus = true;
		this.SubmitButton.Name = "SubmitButton";
		this.SubmitButton.UseUnderline = true;
		this.SubmitButton.Label = global::Mono.Unix.Catalog.GetString("Обчислити");
		this.RootContainer.Add(this.SubmitButton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.RootContainer[this.SubmitButton]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.RootContainer);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SubmitButton.Clicked += new global::System.EventHandler(this.HandleSubmit);
	}
}
